"""
Refined numerics for the weighted zero-sum bound in the thesis draft.

This version incorporates the second estimate of Chirre--Helfgott
Proposition 7.3 whenever its hypotheses hold.  For U >= 2*pi*e and
T >= 3U, the logarithmic-integral contribution to B_phi(U,T) is bounded by

    T/(4*pi^2) * [
        log(T/(2*pi))^2 - log(U/(2*pi))^2
        - 2*C1*log(e*T/(2*pi)) + 2*C2
    ],

where C1 and C2 are the constants from CH Lemma C.3.  When T < 3U the
script automatically falls back to the first, coarser estimate.

The primary comparison is

    refined hybrid zero bound
        versus
    CH Proposition 7.7 at the verified height H0.

For diagnosis, the script also records:

* the old hybrid bound obtained from the coarse Proposition 7.3 estimate;
* a coarse CH benchmark with coefficient log(T/(2*pi))^2/(2*pi);
* each of the six low-real-part and three high-real-part components;
* the gain produced by the refined Proposition 7.3 estimate;
* sampled crossover brackets for

      pi/T + hybrid < pi/H0 + CH(H0);
* a compact set of presentation-ready plots that compare the zero-sum
  bounds directly, rather than displaying only very large global ratios.

Because the current high-real-part estimate is independent of sigma_1 and
the low-real-part bound is increasing in sigma_1, the default computation
uses sigma_1 = 1/2 as notation for the limiting value sigma_1 -> 1/2+.
It is not asserting that the strict hypothesis sigma_1 > 1/2 has changed.

The deterministic sweep includes near-threshold values of x and a dense
large-x grid through log10(x)=2700, with extra resolution across the
predicted crossover region.

By default the plotting stage writes four supervisor-facing figures:

* a near-threshold decomposition of the remaining discrepancy from CH;
* absolute zero-sum bounds for representative truncation heights;
* a low/high-real-part decomposition at T=10 H0;
* the best zero-sum ratio attained at each tested T/H0.

The original global diagnostic plots can still be generated by setting
``include_diagnostic_plots=True`` in ``run_test_suite``.

Run with:

    sage weighted_zero_sum_numerics_supervisor.py

The exact low-zero sums use Sage's optional Odlyzko database. Install it with:

    sage -i database_odlyzko_zeta
"""

from sage.all import RealField, pi, log, exp, sqrt, cot, zeta
from sage.databases.odlyzko import zeta_zeros

import csv
import random
from pathlib import Path


# =============================================================================
# CONSTANTS
# =============================================================================

PREC = 100
R = RealField(prec=PREC)
PI = R(pi)
E = exp(R(1))
TWO_PI = R(2) * PI
LOG_10 = log(R(10))

# Exact Platt--Trudgian verification height quoted by Chirre--Helfgott.
DEFAULT_H0 = R("3000175332800")

# Provisional zero-free-region constant used in the draft.
DEFAULT_ZFR_R = R("5.558691")

# Low-zero cutoff used in the numerical decomposition.
DEFAULT_T0 = R("20000")

# The uniform simplified-weight bound is worst at |xi|=1.
DEFAULT_XI = R(1)

# The endpoint value is interpreted as sigma_1 -> 1/2+.
DEFAULT_SIGMA_LIMIT = R("0.5")

# Refined Proposition 7.3 constants.  We evaluate the exponentially
# convergent correction described in CH Lemma C.3, rather than summing the
# original slowly convergent series directly.
CH_CONSTANT_TERMS = 50


def _compute_ch_constant(k, terms=CH_CONSTANT_TERMS):
    if k == 1:
        base = R(3) / R(2) - R(2) * log(R(2))
    elif k == 2:
        base = R(7) / R(4) - PI**2 / R(6)
    else:
        raise ValueError("Only C1 and C2 are required")

    correction = R(0)
    for n in range(1, terms + 1):
        two_n = R(2 * n)
        coefficient = (
            R(1) / two_n**k
            - R(2) / (two_n + R(1))**k
            + R(1) / (two_n + R(2))**k
        )
        correction += (R(zeta(2 * n)) - R(1)) * coefficient

    return base + correction


CH_C1 = _compute_ch_constant(1)
CH_C2 = _compute_ch_constant(2)


# =============================================================================
# BASIC HELPERS AND VALIDATION
# =============================================================================


def _validate_height(name, value):
    value = R(value)
    if value <= 0:
        raise ValueError(f"{name} must be positive")
    return value


def _validate_parameters(L, H0, T, sigma1, t0, zfr_R, xi):
    L = R(L)
    H0 = _validate_height("H0", H0)
    T = _validate_height("T", T)
    sigma1 = R(sigma1)
    t0 = _validate_height("t0", t0)
    zfr_R = _validate_height("zfr_R", zfr_R)
    xi = R(xi)

    if T <= H0:
        raise ValueError("Require T > H0")
    if not (R("0.5") <= sigma1 < R(1)):
        raise ValueError("Require 1/2 <= sigma1 < 1")
    if abs(xi) > 1:
        raise ValueError("Require -1 <= xi <= 1")
    if t0 < TWO_PI * E:
        raise ValueError("Require t0 >= 2*pi*e")
    if t0 >= H0:
        raise ValueError("Require t0 < H0")
    if L <= log(T):
        raise ValueError("Require x > T, equivalently log(x) > log(T)")

    return L, H0, T, sigma1, t0, zfr_R, xi


def _format_real(value, significant_digits=8):
    """Format arbitrary-size Sage reals without converting huge values to float."""
    value = R(value)
    if value == 0:
        return "0"

    sign = "-" if value < 0 else ""
    magnitude = abs(value)
    exponent = int((log(magnitude) / LOG_10).floor())

    if -4 <= exponent < significant_digits:
        decimals = max(0, significant_digits - exponent - 1)
        return sign + f"{float(magnitude):.{decimals}f}".rstrip("0").rstrip(".")

    mantissa = magnitude / (R(10) ** exponent)
    return sign + f"{float(mantissa):.{significant_digits - 1}f}e{exponent:+d}"


def _format_ratio_label(ratio):
    """Give nearby T/H0 ratios distinct and stable human-readable labels."""
    ratio = R(ratio)
    delta = ratio - R(1)

    if R(0) < delta < R("0.001"):
        mantissa_text, exponent_text = f"{float(delta):.3e}".split("e")
        mantissa_text = mantissa_text.rstrip("0").rstrip(".")
        exponent = int(exponent_text)
        return f"1+{mantissa_text}e{exponent:+d}"

    return _format_real(ratio, significant_digits=9)


# =============================================================================
# CHIRRE--HELFGOTT REAL-AXIS WEIGHT AND EXACT LOW-ZERO SUMS
# =============================================================================


def F_weight(u):
    r"""
    Compute

        F(u) = 1/pi - (1-u) cot(pi(1-u)),  0 < u <= 1.
    """
    u = R(u)
    if u <= 0 or u > 1:
        raise ValueError("F_weight requires 0 < u <= 1")

    v = R(1) - u

    if abs(v) < R("1e-12"):
        return (
            PI * v**2 / R(3)
            + PI**3 * v**4 / R(45)
            + R(2) * PI**5 * v**6 / R(945)
        )

    if u <= R("0.5"):
        return R(1) / PI + (R(1) - u) * cot(PI * u)

    return R(1) / PI - v * cot(PI * v)


def simplified_weight(t, T, xi=DEFAULT_XI):
    r"""Compute |F(t/T) + xi(1-t/T)i|."""
    t = R(t)
    T = _validate_height("T", T)
    xi = R(xi)

    if t <= 0 or t > T:
        raise ValueError("Require 0 < t <= T")
    if abs(xi) > 1:
        raise ValueError("Require -1 <= xi <= 1")

    u = t / T
    return sqrt(F_weight(u)**2 + xi**2 * (R(1) - u)**2)


def load_zero_ordinates(t0):
    """Return all Odlyzko zero ordinates gamma <= t0."""
    t0 = _validate_height("t0", t0)

    try:
        all_zeros = zeta_zeros()
    except (RuntimeError, OSError) as exc:
        raise RuntimeError(
            "Could not load the Odlyzko zero database. Install it with "
            "`sage -i database_odlyzko_zeta`."
        ) from exc

    selected = []
    for gamma in all_zeros:
        gamma = R(gamma)
        if gamma > t0:
            break
        selected.append(gamma)

    if not selected:
        raise RuntimeError(f"No zero ordinates were found below t0={t0}")

    if selected[-1] <= t0 and len(selected) == len(all_zeros):
        raise RuntimeError(
            "The requested t0 exceeds the range of the installed Odlyzko database."
        )

    return selected


def exact_low_zero_sums(zero_ordinates, t0, T, xi=DEFAULT_XI):
    r"""
    Compute

        S_low(t0;T,xi) = sum_{0<gamma<=t0} phi_{T,xi}(gamma),
        S_1(t0)        = sum_{0<gamma<=t0} 1/gamma^2.
    """
    t0 = R(t0)
    T = R(T)
    xi = R(xi)

    slow = R(0)
    s1 = R(0)
    count = 0

    for gamma in zero_ordinates:
        gamma = R(gamma)
        if gamma > t0:
            break
        slow += simplified_weight(gamma, T, xi)
        s1 += R(1) / gamma**2
        count += 1

    return {
        "slow": slow,
        "s1": s1,
        "number_low_zeros": count,
    }


# =============================================================================
# AUXILIARY ANALYTIC BOUNDS
# =============================================================================


def B_weight_details(U, T, use_refined=True):
    r"""
    Return B_phi(U,T) and its components.

    The refined Proposition 7.3 estimate is used only when

        U >= 2*pi*e  and  T >= 3U.

    Otherwise this function returns the original equation-(143) bound.
    """
    U = _validate_height("U", U)
    T = _validate_height("T", T)
    if T < U:
        raise ValueError("Require T >= U")

    log_T = log(T / TWO_PI)
    log_U = log(U / TWO_PI)

    coarse_main = T / (R(4) * PI**2) * (log_T**2 - log_U**2)

    refined_hypotheses = U >= TWO_PI * E and T >= R(3) * U
    refinement_saving = R(0)

    if use_refined and refined_hypotheses:
        refinement_saving = (
            T / (R(4) * PI**2)
            * (
                R(2) * CH_C1 * log(E * T / TWO_PI)
                - R(2) * CH_C2
            )
        )

    main_integral = coarse_main - refinement_saving

    endpoint = (
        (R(2) * log(U) / R(5) + R(4))
        * (T / (PI * U) + PI * U / (R(2) * T))
    )

    variation = R(1) / R(5) * (T / (PI * U) - R(1) / PI)
    total = main_integral + endpoint + variation

    return {
        "coarse_main_integral": coarse_main,
        "main_integral": main_integral,
        "refinement_saving": refinement_saving,
        "endpoint": endpoint,
        "variation": variation,
        "total": total,
        "refined_hypotheses": refined_hypotheses,
        "refined_applied": bool(use_refined and refined_hypotheses),
    }


def B_weight(U, T, use_refined=True):
    return B_weight_details(U, T, use_refined=use_refined)["total"]


def B1(U, T):
    r"""B_1(U,T) from equation (155)."""
    U = _validate_height("U", U)
    T = _validate_height("T", T)
    if T < U:
        raise ValueError("Require T >= U")

    integral = R(1) / TWO_PI * (
        (log(U / TWO_PI) + R(1)) / U
        - (log(T / TWO_PI) + R(1)) / T
    )
    endpoint = R(1) / U**2 * (R(2) * log(U) / R(5) + R(4))
    variation = R(1) / R(10) * (R(1) / U**2 - R(1) / T**2)

    return integral + endpoint + variation


def B2(U, T):
    r"""B_2(U,T) from equation (158)."""
    U = _validate_height("U", U)
    T = _validate_height("T", T)
    if T < U:
        raise ValueError("Require T >= U")

    return (
        T / TWO_PI * log(T / (TWO_PI * E))
        - U / TWO_PI * log(U / (TWO_PI * E))
        + log(T) / R(5)
        + log(U) / R(5)
        + R(4)
    )


def N_plus_bound(T):
    r"""N^+(T) = T/(2*pi) log(T/(2*pi))."""
    T = _validate_height("T", T)
    return T / TWO_PI * log(T / TWO_PI)


# =============================================================================
# WEIGHTED ZERO-SUM BOUNDS
# =============================================================================


def low_real_part_bound(
    L,
    H0,
    T,
    sigma1,
    t0,
    low_sums,
    use_refined_weight=True,
):
    """Compute Proposition 38, retaining all six components."""
    L = R(L)
    H0 = R(H0)
    T = R(T)
    sigma1 = R(sigma1)
    t0 = R(t0)

    x_half = exp(-L / R(2))
    x_sigma = exp((sigma1 - R(1)) * L)

    slow = R(low_sums["slow"])
    s1 = R(low_sums["s1"])

    weight_t0 = B_weight_details(t0, T, use_refined=use_refined_weight)
    weight_H0 = B_weight_details(H0, T, use_refined=use_refined_weight)

    weight_base = TWO_PI / T * x_half * (slow + weight_t0["total"])
    weight_tail = (
        TWO_PI / T
        * R("0.5")
        * (x_sigma - x_half)
        * weight_H0["total"]
    )

    reciprocal_base = x_half * (s1 + B1(t0, T))
    reciprocal_tail = (
        sigma1 * x_sigma - R("0.5") * x_half
    ) * B1(H0, T)

    error_base = (
        R("4.78") * PI / T**2 * x_half * N_plus_bound(T)
    )
    error_tail = (
        PI / T**2
        * (
            (R(2) + R("0.78") * sigma1) * x_sigma
            - R("2.39") * x_half
        )
        * B2(H0, T)
    )

    total = (
        weight_base
        + weight_tail
        + reciprocal_base
        + reciprocal_tail
        + error_base
        + error_tail
    )

    return {
        "low_weight_base": weight_base,
        "low_weight_tail": weight_tail,
        "low_reciprocal_base": reciprocal_base,
        "low_reciprocal_tail": reciprocal_tail,
        "low_error_base": error_base,
        "low_error_tail": error_tail,
        "low_total": total,
        "Bweight_t0_total": weight_t0["total"],
        "Bweight_t0_coarse_main": weight_t0["coarse_main_integral"],
        "Bweight_t0_main": weight_t0["main_integral"],
        "Bweight_t0_refinement_saving": weight_t0["refinement_saving"],
        "Bweight_t0_endpoint": weight_t0["endpoint"],
        "Bweight_t0_variation": weight_t0["variation"],
        "Bweight_t0_refined_applied": weight_t0["refined_applied"],
        "Bweight_H0_total": weight_H0["total"],
        "Bweight_H0_coarse_main": weight_H0["coarse_main_integral"],
        "Bweight_H0_main": weight_H0["main_integral"],
        "Bweight_H0_refinement_saving": weight_H0["refinement_saving"],
        "Bweight_H0_endpoint": weight_H0["endpoint"],
        "Bweight_H0_variation": weight_H0["variation"],
        "Bweight_H0_refined_applied": weight_H0["refined_applied"],
    }


def high_real_part_bound(L, H0, T, zfr_R, use_refined_weight=True):
    """Compute Proposition 39, retaining all three bracket components."""
    L = R(L)
    H0 = R(H0)
    T = R(T)
    zfr_R = R(zfr_R)

    zfr_factor = exp(-L / (zfr_R * log(T)))
    weight_H0 = B_weight_details(H0, T, use_refined=use_refined_weight)

    weight_bracket = TWO_PI / T * weight_H0["total"]
    reciprocal_bracket = R(2) * B1(H0, T)
    error_bracket = R("5.56") * PI / T**2 * B2(H0, T)

    bracket = weight_bracket + reciprocal_bracket + error_bracket

    return {
        "zfr_factor": zfr_factor,
        "high_weight_bracket": weight_bracket,
        "high_reciprocal_bracket": reciprocal_bracket,
        "high_error_bracket": error_bracket,
        "high_weight_part": zfr_factor * weight_bracket,
        "high_reciprocal_part": zfr_factor * reciprocal_bracket,
        "high_error_part": zfr_factor * error_bracket,
        "high_bracket": bracket,
        "high_total": zfr_factor * bracket,
    }


def hybrid_zero_bound(
    L,
    H0,
    T,
    sigma1,
    t0,
    zfr_R,
    low_sums,
    use_refined_weight=True,
):
    """Return Corollary 41 and all retained components."""
    low = low_real_part_bound(
        L=L,
        H0=H0,
        T=T,
        sigma1=sigma1,
        t0=t0,
        low_sums=low_sums,
        use_refined_weight=use_refined_weight,
    )
    high = high_real_part_bound(
        L=L,
        H0=H0,
        T=T,
        zfr_R=zfr_R,
        use_refined_weight=use_refined_weight,
    )

    return {
        **low,
        **high,
        "hybrid_zero_bound": low["low_total"] + high["high_total"],
    }


# =============================================================================
# CH BENCHMARKS
# =============================================================================


def ch_refined_coefficient(T):
    r"""Coefficient in CH Proposition 7.7."""
    T = _validate_height("T", T)
    y = log(T / TWO_PI)
    return y**2 / TWO_PI - R("1.01") * y / (R(6) * PI)


def ch_coarse_coefficient(T):
    r"""CH-style benchmark before the negative linear correction."""
    T = _validate_height("T", T)
    y = log(T / TWO_PI)
    return y**2 / TWO_PI


def ch_refined_zero_bound(L, T):
    return exp(-R(L) / R(2)) * ch_refined_coefficient(T)


def ch_coarse_zero_bound(L, T):
    return exp(-R(L) / R(2)) * ch_coarse_coefficient(T)


# =============================================================================
# PARAMETER SWEEP
# =============================================================================


def default_T_ratios():
    return [
        R("1.00000001"),
        R("1.000001"),
        R("1.0001"),
        R("1.001"),
        R("1.01"),
        R("1.1"),
        R("2"),
        R("10"),
        R("100"),
    ]


def default_near_threshold_offsets():
    r"""Values of log(x/T), retaining the original near/moderate-x grid."""
    return [
        R("0.001"),
        R("0.01"),
        R("0.1"),
        R("0.5"),
        R("1"),
        R("2"),
        R("5"),
        R("10"),
        R("20"),
        R("40"),
        R("80"),
        R("160"),
        R("320"),
        R("640"),
    ]


def default_log10_x_targets():
    """Large-x targets, dense across the expected crossover window."""
    targets = [
        R("500"),
        R("1000"),
        R("1500"),
        R("1750"),
        R("1850"),
        R("1900"),
    ]
    targets.extend(R(value) for value in range(1950, 2626, 25))
    targets.extend([R("2650"), R("2700")])
    return targets


def default_sigma_values():
    """Use the limiting endpoint sigma_1 -> 1/2+ by default."""
    return [DEFAULT_SIGMA_LIMIT]


def boundary_parameters(
    H0=DEFAULT_H0,
    t0=DEFAULT_T0,
    zfr_R=DEFAULT_ZFR_R,
    xi=DEFAULT_XI,
    T_ratios=None,
    near_threshold_offsets=None,
    log10_x_targets=None,
    sigma_values=None,
):
    """Generate the deterministic near-threshold and large-x grids."""
    H0 = R(H0)
    t0 = R(t0)
    zfr_R = R(zfr_R)
    xi = R(xi)

    if T_ratios is None:
        T_ratios = default_T_ratios()
    if near_threshold_offsets is None:
        near_threshold_offsets = default_near_threshold_offsets()
    if log10_x_targets is None:
        log10_x_targets = default_log10_x_targets()
    if sigma_values is None:
        sigma_values = default_sigma_values()

    parameters = []

    for ratio in T_ratios:
        ratio = R(ratio)
        if ratio <= 1:
            raise ValueError("Every T/H0 ratio must exceed 1")

        T = H0 * ratio
        log_T = log(T)
        log10_T = log_T / LOG_10
        L_values = {}

        for offset in near_threshold_offsets:
            offset = R(offset)
            if offset <= 0:
                raise ValueError("Every log(x/T) offset must be positive")
            L_values[str(log_T + offset)] = (log_T + offset, "boundary_offset")

        for target in log10_x_targets:
            target = R(target)
            if target <= log10_T:
                continue
            L = target * LOG_10
            L_values[str(L)] = (L, "boundary_log10")

        for L, sample_type in L_values.values():
            for sigma1 in sigma_values:
                parameters.append({
                    "L": L,
                    "H0": H0,
                    "T": T,
                    "T_ratio": ratio,
                    "log_x_offset": L - log_T,
                    "sigma1": R(sigma1),
                    "t0": t0,
                    "zfr_R": zfr_R,
                    "xi": xi,
                    "sample_type": sample_type,
                })

    return parameters


def _log_uniform(rng, lower, upper):
    lower = R(lower)
    upper = R(upper)
    if lower <= 0 or upper <= lower:
        raise ValueError("Require 0 < lower < upper")
    u = R(str(rng.random()))
    return exp(log(lower) + u * (log(upper) - log(lower)))


def _uniform(rng, lower, upper):
    lower = R(lower)
    upper = R(upper)
    if upper <= lower:
        raise ValueError("Require lower < upper")
    u = R(str(rng.random()))
    return lower + u * (upper - lower)


def sample_parameters(
    n_samples,
    H0=DEFAULT_H0,
    t0=DEFAULT_T0,
    zfr_R=DEFAULT_ZFR_R,
    xi=DEFAULT_XI,
    T_ratios=None,
    sigma_values=None,
    max_log10_x=R("2700"),
    seed=2026,
):
    """
    Generate random slices using a mixture of near-threshold and broad
    log10(x) sampling.  Each slice is evaluated at the supplied sigma grid.
    """
    if T_ratios is None:
        T_ratios = default_T_ratios()
    if sigma_values is None:
        sigma_values = default_sigma_values()

    rng = random.Random(seed)
    H0 = R(H0)
    t0 = R(t0)
    zfr_R = R(zfr_R)
    xi = R(xi)
    max_log10_x = R(max_log10_x)
    ratios = [R(value) for value in T_ratios]
    sigma_values = [R(value) for value in sigma_values]

    parameters = []

    for _ in range(n_samples):
        ratio = ratios[rng.randrange(len(ratios))]
        T = H0 * ratio
        log_T = log(T)
        log10_T = log_T / LOG_10

        if rng.random() < 0.5:
            offset = _log_uniform(rng, R("1e-3"), R("1e3"))
            L = log_T + offset
            sample_type = "random_offset"
        else:
            target = _uniform(rng, log10_T + R("1e-6"), max_log10_x)
            L = target * LOG_10
            offset = L - log_T
            sample_type = "random_log10"

        for sigma1 in sigma_values:
            parameters.append({
                "L": L,
                "H0": H0,
                "T": T,
                "T_ratio": ratio,
                "log_x_offset": offset,
                "sigma1": sigma1,
                "t0": t0,
                "zfr_R": zfr_R,
                "xi": xi,
                "sample_type": sample_type,
            })

    return parameters


# =============================================================================
# SAMPLE EVALUATION
# =============================================================================


def evaluate_point(params, low_sums):
    """Evaluate one point and retain refined, coarse, and component data."""
    L, H0, T, sigma1, t0, zfr_R, xi = _validate_parameters(
        params["L"],
        params["H0"],
        params["T"],
        params["sigma1"],
        params["t0"],
        params["zfr_R"],
        params["xi"],
    )

    refined_hybrid = hybrid_zero_bound(
        L=L,
        H0=H0,
        T=T,
        sigma1=sigma1,
        t0=t0,
        zfr_R=zfr_R,
        low_sums=low_sums,
        use_refined_weight=True,
    )
    coarse_hybrid = hybrid_zero_bound(
        L=L,
        H0=H0,
        T=T,
        sigma1=sigma1,
        t0=t0,
        zfr_R=zfr_R,
        low_sums=low_sums,
        use_refined_weight=False,
    )

    hybrid_zero = refined_hybrid["hybrid_zero_bound"]
    coarse_hybrid_zero = coarse_hybrid["hybrid_zero_bound"]

    ch_H0 = ch_refined_zero_bound(L, H0)
    ch_same_T = ch_refined_zero_bound(L, T)
    ch_coarse_H0 = ch_coarse_zero_bound(L, H0)
    ch_coarse_same_T = ch_coarse_zero_bound(L, T)

    truncation_H0 = PI / H0
    truncation_T = PI / T

    ch_H0_combined = truncation_H0 + ch_H0
    ch_coarse_H0_combined = truncation_H0 + ch_coarse_H0
    hybrid_combined = truncation_T + hybrid_zero

    zero_ratio_H0 = hybrid_zero / ch_H0
    zero_ratio_coarse_H0 = hybrid_zero / ch_coarse_H0
    zero_ratio_same_T = hybrid_zero / ch_same_T
    combined_ratio = hybrid_combined / ch_H0_combined
    combined_ratio_coarse_CH = hybrid_combined / ch_coarse_H0_combined
    combined_margin = ch_H0_combined - hybrid_combined

    refinement_gain = coarse_hybrid_zero - hybrid_zero
    refinement_fraction = refinement_gain / coarse_hybrid_zero
    high_fraction = refined_hybrid["high_total"] / hybrid_zero

    return {
        "sample_type": params.get("sample_type", "unspecified"),
        "H0": H0,
        "T": T,
        "T_ratio": T / H0,
        "t0": t0,
        "sigma1": sigma1,
        "sigma1_is_endpoint_limit": sigma1 == R("0.5"),
        "xi": xi,
        "zfr_R": zfr_R,
        "L": L,
        "log10_x": L / LOG_10,
        "log_x_offset": L - log(T),
        "number_low_zeros": low_sums["number_low_zeros"],
        "slow": low_sums["slow"],
        "s1": low_sums["s1"],
        **refined_hybrid,
        "coarse_hybrid_zero_bound": coarse_hybrid_zero,
        "refinement_gain": refinement_gain,
        "refinement_fraction": refinement_fraction,
        "refined_over_coarse_hybrid": hybrid_zero / coarse_hybrid_zero,
        "ch_H0_zero_bound": ch_H0,
        "ch_same_T_zero_bound": ch_same_T,
        "ch_coarse_H0_zero_bound": ch_coarse_H0,
        "ch_coarse_same_T_zero_bound": ch_coarse_same_T,
        "zero_ratio_H0": zero_ratio_H0,
        "zero_ratio_coarse_H0": zero_ratio_coarse_H0,
        "zero_ratio_same_T": zero_ratio_same_T,
        "log10_zero_ratio_H0": log(zero_ratio_H0) / LOG_10,
        "log10_zero_ratio_coarse_H0": log(zero_ratio_coarse_H0) / LOG_10,
        "truncation_H0": truncation_H0,
        "truncation_T": truncation_T,
        "truncation_saving": truncation_H0 - truncation_T,
        "ch_H0_combined": ch_H0_combined,
        "ch_coarse_H0_combined": ch_coarse_H0_combined,
        "hybrid_combined": hybrid_combined,
        "combined_ratio": combined_ratio,
        "combined_ratio_coarse_CH": combined_ratio_coarse_CH,
        "log10_combined_ratio": log(combined_ratio) / LOG_10,
        "combined_margin": combined_margin,
        "hybrid_combined_wins": combined_margin > 0,
        "high_fraction": high_fraction,
    }


def evaluate_samples(parameters, zero_ordinates, progress_every=250):
    """Evaluate all points, caching exact low-zero sums for each T."""
    results = []
    total = len(parameters)
    low_sum_cache = {}

    for index, params in enumerate(parameters, start=1):
        cache_key = (
            str(R(params["T"])),
            str(R(params["t0"])),
            str(abs(R(params["xi"]))),
        )

        if cache_key not in low_sum_cache:
            low_sum_cache[cache_key] = exact_low_zero_sums(
                zero_ordinates=zero_ordinates,
                t0=params["t0"],
                T=params["T"],
                xi=params["xi"],
            )

        results.append(evaluate_point(params, low_sum_cache[cache_key]))

        if progress_every and index % progress_every == 0:
            print(f"Evaluated {index}/{total} parameter points")

    return results


# =============================================================================
# OPTIMIZATION AND STATISTICS
# =============================================================================


def select_best_splits(results):
    """Retain the smallest hybrid bound on each (x,T)-slice."""
    best = {}

    for row in results:
        key = (
            str(row["L"]),
            str(row["H0"]),
            str(row["T"]),
            str(row["t0"]),
            str(row["xi"]),
            str(row["zfr_R"]),
        )

        if key not in best or row["hybrid_zero_bound"] < best[key]["hybrid_zero_bound"]:
            best[key] = row

    return list(best.values())


def _quantile(values, q):
    if not values:
        raise ValueError("Cannot compute a quantile of empty data")

    q = R(q)
    if q < 0 or q > 1:
        raise ValueError("Require 0 <= q <= 1")

    values = sorted(R(value) for value in values)
    if len(values) == 1:
        return values[0]

    position = q * R(len(values) - 1)
    lower_index = int(position.floor())
    upper_index = int(position.ceil())

    if lower_index == upper_index:
        return values[lower_index]

    weight = position - lower_index
    return (
        (R(1) - weight) * values[lower_index]
        + weight * values[upper_index]
    )


def summarize_results(results):
    if not results:
        raise ValueError("No results to summarize")

    return {
        "number_points": len(results),
        "number_combined_wins": sum(row["hybrid_combined_wins"] for row in results),
        "minimum_zero_ratio": min(row["zero_ratio_H0"] for row in results),
        "median_zero_ratio": _quantile(
            [row["zero_ratio_H0"] for row in results], R("0.5")
        ),
        "maximum_zero_ratio": max(row["zero_ratio_H0"] for row in results),
        "minimum_coarse_CH_ratio": min(
            row["zero_ratio_coarse_H0"] for row in results
        ),
        "median_coarse_CH_ratio": _quantile(
            [row["zero_ratio_coarse_H0"] for row in results], R("0.5")
        ),
        "minimum_combined_ratio": min(row["combined_ratio"] for row in results),
        "median_combined_ratio": _quantile(
            [row["combined_ratio"] for row in results], R("0.5")
        ),
        "maximum_combined_ratio": max(row["combined_ratio"] for row in results),
        "median_high_fraction": _quantile(
            [row["high_fraction"] for row in results], R("0.5")
        ),
        "maximum_refinement_fraction": max(
            row["refinement_fraction"] for row in results
        ),
        "median_refinement_fraction": _quantile(
            [row["refinement_fraction"] for row in results], R("0.5")
        ),
    }


# =============================================================================
# REPORTING
# =============================================================================


def _print_component(label, value, total, indent="    "):
    fraction = R(0) if total == 0 else R(value) / R(total)
    print(
        f"{indent}{label:<27} = {_format_real(value, 10):>16} "
        f"({100 * float(fraction):9.5f}%)"
    )


def _print_result(row, title=None):
    if title is not None:
        print(title)
        print("-" * len(title))

    sigma_text = "1/2+ (limit)" if row["sigma1_is_endpoint_limit"] else _format_real(row["sigma1"])

    print(f"T/H0                         = {_format_ratio_label(row['T_ratio'])}")
    print(f"log(x/T)                     = {_format_real(row['log_x_offset'], 10)}")
    print(f"log10(x)                     = {_format_real(row['log10_x'], 10)}")
    print(f"sigma_1                      = {sigma_text}")
    print(f"refined hybrid zero bound    = {_format_real(row['hybrid_zero_bound'], 12)}")
    print(f"coarse hybrid zero bound     = {_format_real(row['coarse_hybrid_zero_bound'], 12)}")
    print(f"refinement gain              = {_format_real(row['refinement_gain'], 12)}")
    print(f"refinement reduction         = {100 * float(row['refinement_fraction']):.8g}%")
    print()

    print("  LOW-REAL-PART COMPONENTS")
    _print_component("weight: base", row["low_weight_base"], row["low_total"])
    _print_component("weight: tail", row["low_weight_tail"], row["low_total"])
    _print_component("reciprocal: base", row["low_reciprocal_base"], row["low_total"])
    _print_component("reciprocal: tail", row["low_reciprocal_tail"], row["low_total"])
    _print_component("weight-error: base", row["low_error_base"], row["low_total"])
    _print_component("weight-error: tail", row["low_error_tail"], row["low_total"])
    print(f"    {'low total':<27} = {_format_real(row['low_total'], 10):>16}")
    print()

    print("  HIGH-REAL-PART COMPONENTS")
    _print_component("weight", row["high_weight_part"], row["high_total"])
    _print_component("reciprocal", row["high_reciprocal_part"], row["high_total"])
    _print_component("weight-error", row["high_error_part"], row["high_total"])
    print(f"    {'high total':<27} = {_format_real(row['high_total'], 10):>16}")
    print(f"    {'high fraction of hybrid':<27} = {100 * float(row['high_fraction']):15.8g}%")
    print(f"    {'ZFR factor':<27} = {_format_real(row['zfr_factor'], 10):>16}")
    print()

    print("  PROPOSITION 7.3 DIAGNOSTICS")
    print(f"    C1                           = {_format_real(CH_C1, 14)}")
    print(f"    C2                           = {_format_real(CH_C2, 14)}")
    print(f"    refined B_phi(t0,T) used     = {row['Bweight_t0_refined_applied']}")
    print(f"    B_phi(t0,T) refinement gain  = {_format_real(row['Bweight_t0_refinement_saving'], 10)}")
    print(f"    refined B_phi(H0,T) used     = {row['Bweight_H0_refined_applied']}")
    print(f"    B_phi(H0,T) refinement gain  = {_format_real(row['Bweight_H0_refinement_saving'], 10)}")
    print()

    print(f"CH final zero bound at H0      = {_format_real(row['ch_H0_zero_bound'], 12)}")
    print(f"CH coarse zero bound at H0     = {_format_real(row['ch_coarse_H0_zero_bound'], 12)}")
    print(f"CH final zero bound at same T  = {_format_real(row['ch_same_T_zero_bound'], 12)}")
    print(f"hybrid / CH final(H0)          = {_format_real(row['zero_ratio_H0'], 10)}")
    print(f"hybrid / CH coarse(H0)         = {_format_real(row['zero_ratio_coarse_H0'], 10)}")
    print(f"hybrid / CH final(T), ideal    = {_format_real(row['zero_ratio_same_T'], 10)}")
    print(f"pi/H0 + CH final(H0)           = {_format_real(row['ch_H0_combined'], 12)}")
    print(f"pi/T + refined hybrid          = {_format_real(row['hybrid_combined'], 12)}")
    print(f"combined ratio                 = {_format_real(row['combined_ratio'], 10)}")
    print(f"combined margin                = {_format_real(row['combined_margin'], 12)}")
    print(f"hybrid combined wins           = {row['hybrid_combined_wins']}")
    print()


def report_results(results, number_extreme_points=5):
    optimized = select_best_splits(results)
    summary = summarize_results(optimized)

    print()
    print("=" * 88)
    print("REFINED WEIGHTED ZERO-SUM NUMERICAL REPORT")
    print("=" * 88)
    print(f"Full parameter points:             {len(results)}")
    print(f"Optimized (x,T) slices:            {summary['number_points']}")
    print(f"Combined hybrid wins:              {summary['number_combined_wins']}")
    print(f"C1:                                {_format_real(CH_C1, 14)}")
    print(f"C2:                                {_format_real(CH_C2, 14)}")
    print()
    print("Refined hybrid / CH Proposition 7.7 at H0")
    print("-" * 50)
    print(f"Minimum:                          {_format_real(summary['minimum_zero_ratio'], 10)}")
    print(f"Median:                           {_format_real(summary['median_zero_ratio'], 10)}")
    print(f"Maximum:                          {_format_real(summary['maximum_zero_ratio'], 10)}")
    print()
    print("Refined hybrid / coarse CH benchmark at H0")
    print("-" * 50)
    print(f"Minimum:                          {_format_real(summary['minimum_coarse_CH_ratio'], 10)}")
    print(f"Median:                           {_format_real(summary['median_coarse_CH_ratio'], 10)}")
    print()
    print("(pi/T + refined hybrid) / (pi/H0 + CH final(H0))")
    print("-" * 58)
    print(f"Minimum:                          {_format_real(summary['minimum_combined_ratio'], 10)}")
    print(f"Median:                           {_format_real(summary['median_combined_ratio'], 10)}")
    print(f"Maximum:                          {_format_real(summary['maximum_combined_ratio'], 10)}")
    print(f"Median high-range fraction:       {100 * float(summary['median_high_fraction']):.8g}%")
    print(f"Median Prop. 7.3 reduction:       {100 * float(summary['median_refinement_fraction']):.8g}%")
    print(f"Maximum Prop. 7.3 reduction:      {100 * float(summary['maximum_refinement_fraction']):.8g}%")

    best = sorted(optimized, key=lambda row: row["combined_ratio"])
    worst = sorted(optimized, key=lambda row: row["combined_ratio"], reverse=True)

    print()
    print("=" * 88)
    print("BEST COMBINED COMPARISONS")
    print("=" * 88)
    for index, row in enumerate(best[:number_extreme_points], start=1):
        _print_result(row, f"Best point {index}")

    print("=" * 88)
    print("WORST COMBINED COMPARISONS")
    print("=" * 88)
    for index, row in enumerate(worst[:number_extreme_points], start=1):
        _print_result(row, f"Worst point {index}")

    report_by_T_ratio(optimized)
    report_crossover_brackets(optimized)
    report_split_endpoint(optimized)

    return optimized


def report_by_T_ratio(optimized_results):
    print()
    print("BEST RESULT GROUPED BY T/H0")
    print("-" * 104)
    print(
        "ratio              n   min/final CH   min/coarse CH   min combined   "
        "wins   first win log10(x)"
    )

    ratio_map = {str(row["T_ratio"]): row["T_ratio"] for row in optimized_results}
    ratios = sorted(ratio_map.values())

    for ratio in ratios:
        group = [row for row in optimized_results if row["T_ratio"] == ratio]
        best = min(group, key=lambda row: row["combined_ratio"])
        wins = [row for row in group if row["hybrid_combined_wins"]]
        first_win = min(wins, key=lambda row: row["log10_x"]) if wins else None
        first_win_text = "--" if first_win is None else _format_real(first_win["log10_x"], 8)

        print(
            f"{_format_ratio_label(ratio):<18} "
            f"{len(group):4d} "
            f"{_format_real(min(row['zero_ratio_H0'] for row in group), 7):>14} "
            f"{_format_real(min(row['zero_ratio_coarse_H0'] for row in group), 7):>15} "
            f"{_format_real(best['combined_ratio'], 7):>14} "
            f"{len(wins):6d} "
            f"{first_win_text:>20}"
        )


def report_crossover_brackets(optimized_results):
    print()
    print("SAMPLED COMBINED-COMPARISON CROSSOVER BRACKETS")
    print("-" * 88)
    print("ratio              last sampled loss       first sampled win")

    ratio_map = {str(row["T_ratio"]): row["T_ratio"] for row in optimized_results}

    for ratio in sorted(ratio_map.values()):
        group = sorted(
            [row for row in optimized_results if row["T_ratio"] == ratio],
            key=lambda row: row["log10_x"],
        )

        first_win_index = None
        for index, row in enumerate(group):
            if row["combined_ratio"] <= 1:
                first_win_index = index
                break

        if first_win_index is None:
            loss_text = _format_real(group[-1]["log10_x"], 9)
            print(f"{_format_ratio_label(ratio):<18} > {loss_text:<19} no sampled win")
            continue

        first_win = group[first_win_index]
        if first_win_index == 0:
            last_loss_text = "--"
        else:
            last_loss_text = _format_real(group[first_win_index - 1]["log10_x"], 9)

        print(
            f"{_format_ratio_label(ratio):<18} "
            f"{last_loss_text:>18} "
            f"{_format_real(first_win['log10_x'], 9):>23}"
        )


def report_split_endpoint(optimized_results):
    print()
    print("SPLIT-POINT HANDLING")
    print("-" * 88)
    endpoint_count = sum(row["sigma1_is_endpoint_limit"] for row in optimized_results)
    print(
        "The default sweep evaluates the continuous limiting bound at "
        "sigma_1 -> 1/2+."
    )
    print(f"Endpoint-limit slices: {endpoint_count}/{len(optimized_results)}")


# =============================================================================
# CSV OUTPUT
# =============================================================================


def write_results_csv(results, filename):
    if not results:
        raise ValueError("No results to write")

    path = Path(filename)
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = list(results[0].keys())

    with path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for row in results:
            writer.writerow({
                key: str(value) if not isinstance(value, bool) else value
                for key, value in row.items()
            })

    print(f"Wrote CSV: {path}")


# =============================================================================
# PLOTS
# =============================================================================


def _plot_rows(optimized_results):
    """Use deterministic rows for smooth, reproducible presentation plots."""
    boundary = [
        row for row in optimized_results
        if str(row["sample_type"]).startswith("boundary")
    ]
    return boundary if boundary else optimized_results


def _ratio_key(value):
    return str(R(value))


def _available_ratio_map(rows):
    return {_ratio_key(row["T_ratio"]): row["T_ratio"] for row in rows}


def _select_available_ratios(rows, requested):
    """Return requested ratios that are present, preserving requested order."""
    available = _available_ratio_map(rows)
    selected = []

    for value in requested:
        key = _ratio_key(value)
        if key in available:
            selected.append(available[key])

    return selected


def _group_for_ratio(rows, ratio, sample_type=None):
    group = [row for row in rows if row["T_ratio"] == ratio]
    if sample_type is not None:
        group = [row for row in group if row["sample_type"] == sample_type]
    return sorted(group, key=lambda row: row["log10_x"])


def _log10_positive(value):
    value = R(value)
    if value <= 0:
        raise ValueError("Logarithmic plot values must be positive")
    return float(log(value) / LOG_10)


def _save_figure(fig, filename):
    fig.tight_layout()
    fig.savefig(filename, dpi=250, bbox_inches="tight")
    import matplotlib.pyplot as plt
    plt.close(fig)
    print(f"Wrote plot: {filename}")


def make_supervisor_plots(optimized_results, output_directory="output"):
    """
    Save presentation-ready plots that answer four concrete questions:

    1. Near T=H0, where does the remaining discrepancy from CH come from?
    2. How do the absolute zero-sum bounds decay as x grows?
    3. Which part of the hybrid bound dominates for a representative T?
    4. How rapidly does the best zero-sum comparison deteriorate as T/H0 grows?

    The plots use deterministic grid points only.  Random samples remain in
    the CSV and terminal report but are intentionally omitted from figures.
    """
    import matplotlib.pyplot as plt

    output_path = Path(output_directory)
    output_path.mkdir(parents=True, exist_ok=True)
    rows = _plot_rows(optimized_results)

    # ---------------------------------------------------------------------
    # Plot 1: near-threshold decomposition, zoomed into the actual residual.
    # ---------------------------------------------------------------------
    near_ratios = _select_available_ratios(rows, [R("1.00000001")])
    if near_ratios:
        ratio = near_ratios[0]
        group = [
            row for row in _group_for_ratio(rows, ratio, "boundary_offset")
            if row["log_x_offset"] <= R("2")
        ]

        if group:
            x_values = [float(row["log_x_offset"]) for row in group]

            refined_excess = [
                100 * float(row["zero_ratio_H0"] - R(1))
                for row in group
            ]
            coarse_excess = [
                100 * float(
                    row["coarse_hybrid_zero_bound"] / row["ch_H0_zero_bound"]
                    - R(1)
                )
                for row in group
            ]
            low_excess = [
                100 * float(
                    row["low_total"] / row["ch_H0_zero_bound"] - R(1)
                )
                for row in group
            ]
            high_contribution = [
                100 * float(row["high_total"] / row["ch_H0_zero_bound"])
                for row in group
            ]

            fig, ax = plt.subplots(figsize=(9, 5.5))
            ax.plot(
                x_values,
                refined_excess,
                marker="o",
                linewidth=2.2,
                label="Refined hybrid: excess over CH",
            )
            ax.plot(
                x_values,
                coarse_excess,
                marker="s",
                linewidth=1.8,
                linestyle="--",
                label="Coarse hybrid: excess over CH",
            )
            ax.plot(
                x_values,
                low_excess,
                marker="^",
                linewidth=1.8,
                label="Refined low range: excess over CH",
            )
            ax.plot(
                x_values,
                high_contribution,
                marker="D",
                linewidth=1.8,
                label="High-range contribution as % of CH",
            )
            ax.axhline(0.0, linewidth=1.2, linestyle=":")
            ax.set_xlabel(r"$\log(x/T)$")
            ax.set_ylabel("Percentage points relative to the CH zero bound")
            ax.set_title(
                "Near-threshold zero-sum comparison\n"
                f"T/H0 = {_format_ratio_label(ratio)}; the remaining loss comes from the high range"
            )
            ax.grid(True, alpha=0.25)
            ax.legend(loc="best", fontsize="small")

            filename = output_path / "weighted_zero_supervisor_near_threshold.png"
            _save_figure(fig, filename)

    # ---------------------------------------------------------------------
    # Plot 2: absolute bounds for a small, representative set of heights.
    # ---------------------------------------------------------------------
    selected_ratios = _select_available_ratios(
        rows,
        [R("1.00000001"), R("2"), R("10"), R("100")],
    )
    if selected_ratios:
        fig, ax = plt.subplots(figsize=(9.5, 6))

        reference_group = _group_for_ratio(
            rows,
            selected_ratios[0],
            "boundary_log10",
        )
        if reference_group:
            ax.plot(
                [float(row["log10_x"]) for row in reference_group],
                [_log10_positive(row["ch_H0_zero_bound"]) for row in reference_group],
                linewidth=2.4,
                linestyle="--",
                label=r"CH zero bound at $H_0$",
            )

        for ratio in selected_ratios:
            group = _group_for_ratio(rows, ratio, "boundary_log10")
            if not group:
                continue
            ax.plot(
                [float(row["log10_x"]) for row in group],
                [_log10_positive(row["hybrid_zero_bound"]) for row in group],
                linewidth=2.0,
                marker="o",
                markersize=3,
                label=f"Hybrid, T/H0={_format_ratio_label(ratio)}",
            )

        ax.set_xlabel(r"$\log_{10}x$")
        ax.set_ylabel(r"$\log_{10}$(weighted zero-sum bound)")
        ax.set_title(
            "Absolute weighted zero-sum bounds\n"
            "The ZFR-controlled hybrid terms decay much more slowly than the CH $x^{-1/2}$ bound"
        )
        ax.grid(True, alpha=0.25)
        ax.legend(loc="upper left", bbox_to_anchor=(1.02, 1), fontsize="small")

        filename = output_path / "weighted_zero_supervisor_absolute_bounds.png"
        _save_figure(fig, filename)

    # ---------------------------------------------------------------------
    # Plot 3: low/high decomposition for a representative enlarged height.
    # ---------------------------------------------------------------------
    component_ratios = _select_available_ratios(rows, [R("10"), R("2"), R("100")])
    if component_ratios:
        ratio = component_ratios[0]
        group = _group_for_ratio(rows, ratio, "boundary_log10")

        if group:
            fig, ax = plt.subplots(figsize=(9.5, 6))
            x_values = [float(row["log10_x"]) for row in group]

            ax.plot(
                x_values,
                [_log10_positive(row["hybrid_zero_bound"]) for row in group],
                linewidth=2.4,
                label="Hybrid total",
            )
            ax.plot(
                x_values,
                [_log10_positive(row["high_total"]) for row in group],
                linewidth=2.0,
                linestyle="--",
                label="High-real-part range (ZFR)",
            )
            ax.plot(
                x_values,
                [_log10_positive(row["low_total"]) for row in group],
                linewidth=2.0,
                linestyle=":",
                label="Low-real-part range",
            )
            ax.plot(
                x_values,
                [_log10_positive(row["ch_H0_zero_bound"]) for row in group],
                linewidth=2.0,
                linestyle="-.",
                label=r"CH zero bound at $H_0$",
            )

            ax.set_xlabel(r"$\log_{10}x$")
            ax.set_ylabel(r"$\log_{10}$(bound)")
            ax.set_title(
                "Decomposition of the hybrid weighted zero sum\n"
                f"Representative case T/H0 = {_format_ratio_label(ratio)}"
            )
            ax.grid(True, alpha=0.25)
            ax.legend(loc="upper left", bbox_to_anchor=(1.02, 1), fontsize="small")

            filename = output_path / "weighted_zero_supervisor_components_T10.png"
            _save_figure(fig, filename)

    # ---------------------------------------------------------------------
    # Plot 4: best zero-sum ratio attained for each tested truncation height.
    # ---------------------------------------------------------------------
    available = sorted(_available_ratio_map(rows).values())
    if available:
        labels = []
        log_best_ratios = []
        exact_best_ratios = []

        for ratio in available:
            group = [row for row in rows if row["T_ratio"] == ratio]
            if not group:
                continue
            best_ratio = min(row["zero_ratio_H0"] for row in group)
            labels.append(_format_ratio_label(ratio))
            log_best_ratios.append(_log10_positive(best_ratio))
            exact_best_ratios.append(best_ratio)

        fig, ax = plt.subplots(figsize=(10, 5.8))
        positions = list(range(len(labels)))
        bars = ax.bar(positions, log_best_ratios)
        ax.axhline(0.0, linewidth=1.2, linestyle=":")
        ax.set_xticks(positions)
        ax.set_xticklabels(labels, rotation=35, ha="right")
        ax.set_xlabel(r"Truncation-height ratio $T/H_0$")
        ax.set_ylabel(r"$\log_{10}$(best hybrid / CH zero bound)")
        ax.set_title(
            "Best weighted zero-sum comparison at each tested height\n"
            "Zero marks equality with the CH bound"
        )
        ax.grid(True, axis="y", alpha=0.25)

        for bar, ratio_value in zip(bars, exact_best_ratios):
            height = bar.get_height()
            if ratio_value < R("1000"):
                annotation = f"{float(ratio_value):.3g}×"
            else:
                annotation = f"$10^{{{float(log(ratio_value) / LOG_10):.1f}}}$×"
            ax.annotate(
                annotation,
                xy=(bar.get_x() + bar.get_width() / 2, height),
                xytext=(0, 4),
                textcoords="offset points",
                ha="center",
                va="bottom",
                fontsize="x-small",
            )

        filename = output_path / "weighted_zero_supervisor_best_by_height.png"
        _save_figure(fig, filename)


def make_diagnostic_plots(optimized_results, output_directory="output"):
    """Retain the original global diagnostic plots for internal use."""
    import matplotlib.pyplot as plt

    output_path = Path(output_directory)
    output_path.mkdir(parents=True, exist_ok=True)
    plot_rows = _plot_rows(optimized_results)

    ratio_map = _available_ratio_map(plot_rows)
    ratios = sorted(ratio_map.values())

    fig, ax = plt.subplots(figsize=(9, 5.5))
    for ratio in ratios:
        group = sorted(
            [row for row in plot_rows if row["T_ratio"] == ratio],
            key=lambda row: row["log10_x"],
        )
        ax.plot(
            [float(row["log10_x"]) for row in group],
            [float(row["log10_zero_ratio_H0"]) for row in group],
            marker="o",
            markersize=3,
            label=f"T/H0={_format_ratio_label(ratio)}",
        )

    ax.axhline(0.0, linestyle="--", linewidth=1)
    ax.set_xlabel("log10(x)")
    ax.set_ylabel("log10(refined hybrid / CH final at H0)")
    ax.set_title("Weighted zero-sum comparison (diagnostic)")
    ax.legend(fontsize="small", loc="upper left", bbox_to_anchor=(1.02, 1))
    zero_plot = output_path / "weighted_zero_refined_ratio_diagnostic.png"
    _save_figure(fig, zero_plot)

    fig, ax = plt.subplots(figsize=(9, 5.5))
    for ratio in ratios:
        group = sorted(
            [row for row in plot_rows if row["T_ratio"] == ratio],
            key=lambda row: row["log10_x"],
        )
        ax.plot(
            [float(row["log10_x"]) for row in group],
            [float(row["log10_combined_ratio"]) for row in group],
            marker="o",
            markersize=3,
            label=f"T/H0={_format_ratio_label(ratio)}",
        )

    ax.axhline(0.0, linestyle="--", linewidth=1)
    ax.set_xlabel("log10(x)")
    ax.set_ylabel("log10((pi/T + hybrid)/(pi/H0 + CH final))")
    ax.set_title("Truncation plus weighted-zero comparison (diagnostic)")
    ax.legend(fontsize="small", loc="upper left", bbox_to_anchor=(1.02, 1))
    combined_plot = output_path / "weighted_zero_refined_combined_ratio_diagnostic.png"
    _save_figure(fig, combined_plot)

    fig, ax = plt.subplots(figsize=(9, 5.5))
    for ratio in ratios:
        group = sorted(
            [row for row in plot_rows if row["T_ratio"] == ratio],
            key=lambda row: row["log10_x"],
        )
        ax.plot(
            [float(row["log10_x"]) for row in group],
            [100 * float(row["refinement_fraction"]) for row in group],
            marker="o",
            markersize=3,
            label=f"T/H0={_format_ratio_label(ratio)}",
        )

    ax.set_xlabel("log10(x)")
    ax.set_ylabel("Reduction from refined Proposition 7.3 (%)")
    ax.set_title("Refinement gain in the hybrid bound (diagnostic)")
    ax.legend(fontsize="small", loc="upper left", bbox_to_anchor=(1.02, 1))
    refinement_plot = output_path / "weighted_zero_refinement_gain_diagnostic.png"
    _save_figure(fig, refinement_plot)


def make_plots(
    optimized_results,
    output_directory="output",
    include_diagnostic_plots=False,
):
    """Create supervisor-facing plots, with optional full diagnostic plots."""
    make_supervisor_plots(
        optimized_results,
        output_directory=output_directory,
    )

    if include_diagnostic_plots:
        make_diagnostic_plots(
            optimized_results,
            output_directory=output_directory,
        )


# =============================================================================
# RUN TEST SUITE
# =============================================================================


def run_test_suite(
    number_random_samples=500,
    H0=DEFAULT_H0,
    t0=DEFAULT_T0,
    zfr_R=DEFAULT_ZFR_R,
    xi=DEFAULT_XI,
    output_directory="output",
    seed=2026,
    create_plots=True,
    include_diagnostic_plots=False,
):
    print("Refined Proposition 7.3 constants:")
    print(f"  C1 = {_format_real(CH_C1, 16)}")
    print(f"  C2 = {_format_real(CH_C2, 16)}")

    print("Loading Odlyzko zero ordinates...")
    zero_ordinates = load_zero_ordinates(t0)
    print(f"Loaded {len(zero_ordinates)} zeros with gamma <= {_format_real(t0, 8)}")

    print("Generating deterministic near-threshold and crossover grid...")
    parameters = boundary_parameters(
        H0=H0,
        t0=t0,
        zfr_R=zfr_R,
        xi=xi,
    )

    print(f"Generating {number_random_samples} random (x,T) slices...")
    parameters.extend(
        sample_parameters(
            n_samples=number_random_samples,
            H0=H0,
            t0=t0,
            zfr_R=zfr_R,
            xi=xi,
            max_log10_x=R("2700"),
            seed=seed,
        )
    )

    print(f"Evaluating {len(parameters)} total parameter points...")
    results = evaluate_samples(
        parameters,
        zero_ordinates=zero_ordinates,
        progress_every=250,
    )

    optimized = report_results(results, number_extreme_points=5)

    output_path = Path(output_directory)
    write_results_csv(
        results,
        output_path / f"weighted_zero_refined_all_seed_{seed}.csv",
    )
    write_results_csv(
        optimized,
        output_path / f"weighted_zero_refined_optimized_seed_{seed}.csv",
    )

    if create_plots:
        make_plots(
            optimized,
            output_directory=output_directory,
            include_diagnostic_plots=include_diagnostic_plots,
        )

    return results, optimized


if __name__ == "__main__":
    run_test_suite(
        number_random_samples=500,
        output_directory="output",
        seed=2026,
        create_plots=True,
        include_diagnostic_plots=False,
    )
